### ISSUE TITLE
Installation through HACS

### ISSUE THREAD

**Issue by bazzooka** [clementprevot/home-assistant-idiamant#35]
## Version of the custom_component
The last one 

## Configuration

No specific configuration 

## Describe the bug

I tried to install this plugin through HACS which I think is a good solution because it help me to keep it updated. 
The installation was successful as I can check that all the files are at the right place. 
Unfortunately, I was unable to install it in integration step. I get an error without any information. 

![5AFF8063-68A9-48E6-AA5C-FBC64B6CDC84](https://user-images.githubusercontent.com/377914/162609288-74433342-78e0-4a00-9199-504438d58cd9.png)

Can you help me?

**Comment by clementprevot** [comment]
Hello @bazzooka 

This plugin is not ready yet. I don't even know how you find it 😄 
I'll let you know when the first release is ready.
